source "https://rubygems.org"

group :development, :test do
  gem "byebug", "~> 6.0"
  gem "pry-rails", "~> 0.3"
  gem "spring", "~> 1.4"
  gem "web-console", "~> 2.2"
  gem "thin", "~> 1.6"
  gem "faker", "~> 1.5"
end

group :development do
  gem "bullet", "~> 4.14"
  gem "better_errors", "~> 2.1"
end

group :test do
  gem "cucumber-rails", "~> 1.4", {:require=>false}
  gem "rspec-rails", "~> 3.3"
  gem "factory_girl_rails", "~> 4.5"
  gem "capybara", "~> 2.5"
  gem "database_cleaner", "~> 1.5"
  gem "launchy", "~> 2.4"
  gem "poltergeist", "~> 1.7"
  gem "selenium-webdriver", "~> 2.47"
  gem "capybara-webkit"
  gem "simplecov", "~> 0.10"
end

gem "rails", "~> 4.2"
gem "pg"
gem "sass-rails", "~> 5.0"
gem "uglifier", "~> 2.7"
gem "coffee-rails", "~> 4.1"
gem "jquery-rails", "~> 4.0"
gem "turbolinks", "~> 2.5"
gem "jbuilder", "~> 2.3"
gem "sdoc", "~> 0.4", {:group=>:doc}
gem "bootstrap-sass", "~> 3.3"

gem "simple_form", "~> 3.2"
gem "reform", "~> 2.0"

gem 'country_state_select', path: '../../'